### PR TITLE
deps: relax urllib3 dependency to >=2.2.2,<3

### LINKED ISSUE #1160: ggshield>=1.43.0 is not compatible with urllib3 > 2.6.0
## Environment

- ggshield version>=1.43.0
- Operating system (Linux, macOS, Windows): macOS
- Python version : 3.13.5

## Describe the bug
While attempting to upgrade urllib3 to version 2.6.0 or higher to resolve security vulnerabilities, we discovered that ggshield 1.43.0 is not compatible with newer urllib3 versions. The ggshield package enforces a dependency constraint requiring:
`urllib3 < 2.3.dev0`
This prevents us from upgrading urllib3 to a secure version and blocks vulnerability remediation.

Steps to reproduce:
1. Install Python environment with urllib3 >= 2.6.0
2. Install ggshield==1.43.0

Actual result:
Observe dependency conflict error:
`ggshield requires urllib3<2.3.dev0`

Expected result:
ggshield should support urllib3 >= 2.6.0 or publish a compatible version that removes the restrictive dependency.

### PR DESCRIPTION
**Pull request by alexpasmantier**
## Context
Fixes #1160 

## PR check list

- [ ] As much as possible, the changes include tests (unit and/or functional)
- [ ] If the changes affect the end user (new feature, behavior change, bug fix) then the PR has a changelog entry (see doc/dev/getting-started.md). If the changes do not affect the end user, then the `skip-changelog` label has been added to the PR.

### CODE REVIEW

File: changelog.d/20260217_102505_alexandre.pasmantier_relax_urllib3_pin.md [hunk 1]
```diff
@@ -0,0 +1,3 @@
+### Changed
+
+- Relaxed `urllib3` dependency pin from `~=2.2.2` to `>=2.2.2,<3`, allowing compatibility with newer urllib3 versions (#1160).
```
Comment (sevbch) [inline changelog.d/20260217_102505_alexandre.pasmantier_relax_urllib3_pin.md]: convention is to use infinitive
```suggestion
- Relax `urllib3` dependency pin from `~=2.2.2` to `>=2.2.2,<3`, allowing compatibility with newer urllib3 versions (#1160).
```

File: pyproject.toml [hunk 2]
```diff
@@ -63,7 +63,7 @@ build-backend = "pdm.backend"
 [tool.pdm.resolution.overrides]
 # vcrpy requires urllib3 < 2 if Python is < 3.10, but it works for us with
 # Python 3.9, so force urllib3 version.
-urllib3 = "2.2.3"
+urllib3 = ">=2.2.2"
```
Comment (sevbch) [inline pyproject.toml]: no need for the <3 here?

Comment (alexpasmantier) [reply pyproject.toml]: good catch!

File: pyproject.toml [hunk 3]
```diff
@@ -63,7 +63,7 @@ build-backend = "pdm.backend"
 [tool.pdm.resolution.overrides]
 # vcrpy requires urllib3 < 2 if Python is < 3.10, but it works for us with
```
Comment (sevbch) [inline pyproject.toml:64]: About this comment, did you check if you can re-generate cassettes properly with the bump in urllib3?

You can check by deleting a cassette and re-run the test generating it, and make sure the new cassette generation goes well

Comment (alexpasmantier) [reply pyproject.toml:64]: Yes, works fine ✅ 
Thanks for pointing that out!
